name: Package Electron App as Portable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package-app:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Ensure compatibility with your Electron version

    - name: Install Dependencies
      run: npm install

    - name: Package App
      run: npm run package

    - name: Zip Package
      run: |
        Compress-Archive -Path out/package/* -DestinationPath packaged-app.zip

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: portable-windows-app
        path: packaged-app.zip

