name: Electron Build for Windows
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Node.js modules
      uses: actions/cache@v4
      with:
        path: ~\AppData\Roaming\npm-cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'  # Updated to LTS version
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools wheel
    
    - name: Install npm dependencies
      run: npm install
    
    - name: Rebuild native modules
      run: npm run rebuild
    
    - name: Package Electron app for Windows
      run: npx electron-packager . physicsuniverse --overwrite --platform=win32 --arch=x64 --out=release-builds --prune=true
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: physicsuniverse-win
        path: release-builds/physicsuniverse-win32-x64/
