name: Build and Package Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Match the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Run package script
      run: npm run package

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: packaged-app
        path: out/make/**/*  # This path is an educated guess; adjust as necessary

