name: Package Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  package-app:
    runs-on: windows-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Adjust this as necessary to match your project's Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Package App
      run: npm run package

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-app
        path: out/package/**  # Adjust this path to match where electron-forge outputs the packaged files

